version: 0.0
os: linux
files:
  - source: .
    destination: /home/csrt/apps/csrt
permissions:
  - object: .
    owner: csrt
    group: csrt
hooks:
  AfterInstall:
    - location: CodeDeploy/AfterInstall.sh
      runas: csrt
    - location: CodeDeploy/AfterInstall-root.sh
      runas: root
