version: 0.2

phases:
  install:
    commands:
      - git clone https://github.com/consbio/csrt.git csrt-build
      - (cd csrt-build && git submodule init)
      - (cd csrt-build/javascript && npm install)
  build:
    commands:
      - (cd csrt-build/javascript && npm run-script build)

artifacts:
  files: "csrt-build/**/*"
